import { z } from 'zod';
export declare const COMMERCE_OBJECT_VERSION: "commerce.object.v1";
export declare const productObjectSchema: z.ZodObject<{
    name: z.ZodString;
    categoryId: z.ZodString;
    status: z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Product">;
}, "strip", z.ZodTypeAny, {
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Product";
    name: string;
    categoryId: string;
    version: "commerce.object.v1";
    updatedAt: string;
}, {
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Product";
    name: string;
    categoryId: string;
    version: "commerce.object.v1";
    updatedAt: string;
}>;
export declare const skuObjectSchema: z.ZodObject<{
    skuId: z.ZodString;
    productId: z.ZodString;
    title: z.ZodString;
    status: z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"SKU">;
}, "strip", z.ZodTypeAny, {
    title: string;
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    productId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    skuId: string;
    objectType: "SKU";
    version: "commerce.object.v1";
    updatedAt: string;
}, {
    title: string;
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    productId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    skuId: string;
    objectType: "SKU";
    version: "commerce.object.v1";
    updatedAt: string;
}>;
export declare const categoryObjectSchema: z.ZodObject<{
    name: z.ZodString;
    parentId: z.ZodNullable<z.ZodString>;
    status: z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Category">;
}, "strip", z.ZodTypeAny, {
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Category";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    parentId: string | null;
}, {
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Category";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    parentId: string | null;
}>;
export declare const inventoryObjectSchema: z.ZodObject<{
    skuId: z.ZodString;
    warehouseId: z.ZodString;
    available: z.ZodNumber;
    reserved: z.ZodNumber;
    reorderPoint: z.ZodNumber;
    safetyStock: z.ZodNumber;
    status: z.ZodEnum<["HEALTHY", "LOW", "OUT_OF_STOCK", "FROZEN"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Inventory">;
}, "strip", z.ZodTypeAny, {
    status: "HEALTHY" | "LOW" | "OUT_OF_STOCK" | "FROZEN";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    skuId: string;
    available: number;
    reserved: number;
    reorderPoint: number;
    safetyStock: number;
    objectType: "Inventory";
    version: "commerce.object.v1";
    updatedAt: string;
    warehouseId: string;
}, {
    status: "HEALTHY" | "LOW" | "OUT_OF_STOCK" | "FROZEN";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    skuId: string;
    available: number;
    reserved: number;
    reorderPoint: number;
    safetyStock: number;
    objectType: "Inventory";
    version: "commerce.object.v1";
    updatedAt: string;
    warehouseId: string;
}>;
export declare const channelObjectSchema: z.ZodObject<{
    channelId: z.ZodString;
    platform: z.ZodString;
    shopId: z.ZodString;
    status: z.ZodEnum<["CONNECTED", "READ_ONLY", "DISCONNECTED", "BLOCKED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Channel">;
}, "strip", z.ZodTypeAny, {
    shopId: string;
    status: "BLOCKED" | "CONNECTED" | "READ_ONLY" | "DISCONNECTED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    platform: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Channel";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
}, {
    shopId: string;
    status: "BLOCKED" | "CONNECTED" | "READ_ONLY" | "DISCONNECTED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    platform: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Channel";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
}>;
export declare const orderObjectSchema: z.ZodObject<{
    orderId: z.ZodString;
    channelId: z.ZodString;
    status: z.ZodEnum<["CREATED", "PAID", "FULFILLING", "COMPLETED", "REFUNDED", "CANCELLED"]>;
    totalAmount: z.ZodNumber;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Order">;
}, "strip", z.ZodTypeAny, {
    status: "CREATED" | "PAID" | "FULFILLING" | "COMPLETED" | "REFUNDED" | "CANCELLED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Order";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
    orderId: string;
    totalAmount: number;
}, {
    status: "CREATED" | "PAID" | "FULFILLING" | "COMPLETED" | "REFUNDED" | "CANCELLED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Order";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
    orderId: string;
    totalAmount: number;
}>;
export declare const businessCaseObjectSchema: z.ZodObject<{
    caseId: z.ZodString;
    title: z.ZodString;
    status: z.ZodEnum<["OPEN", "INVESTIGATING", "PROPOSED", "WAITING_HUMAN", "APPROVED", "EXECUTING", "VERIFYING", "CLOSED", "BLOCKED"]>;
    triggerEventId: z.ZodString;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"BusinessCase">;
}, "strip", z.ZodTypeAny, {
    title: string;
    status: "CLOSED" | "OPEN" | "INVESTIGATING" | "PROPOSED" | "WAITING_HUMAN" | "APPROVED" | "EXECUTING" | "VERIFYING" | "BLOCKED";
    caseId: string;
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    triggerEventId: string;
    objectType: "BusinessCase";
    version: "commerce.object.v1";
    updatedAt: string;
}, {
    title: string;
    status: "CLOSED" | "OPEN" | "INVESTIGATING" | "PROPOSED" | "WAITING_HUMAN" | "APPROVED" | "EXECUTING" | "VERIFYING" | "BLOCKED";
    caseId: string;
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    triggerEventId: string;
    objectType: "BusinessCase";
    version: "commerce.object.v1";
    updatedAt: string;
}>;
export declare const campaignObjectSchema: z.ZodObject<{
    campaignId: z.ZodString;
    name: z.ZodString;
    status: z.ZodEnum<["PLANNED", "RUNNING", "PAUSED", "ENDED"]>;
    channelIds: z.ZodArray<z.ZodString, "many">;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Campaign">;
}, "strip", z.ZodTypeAny, {
    status: "PAUSED" | "PLANNED" | "RUNNING" | "ENDED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Campaign";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    campaignId: string;
    channelIds: string[];
}, {
    status: "PAUSED" | "PLANNED" | "RUNNING" | "ENDED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Campaign";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    campaignId: string;
    channelIds: string[];
}>;
export declare const liveSessionObjectSchema: z.ZodObject<{
    liveSessionId: z.ZodString;
    channelId: z.ZodString;
    status: z.ZodEnum<["PLANNED", "LIVE", "ENDED", "CANCELLED"]>;
    scheduledAt: z.ZodString;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"LiveSession">;
}, "strip", z.ZodTypeAny, {
    status: "CANCELLED" | "PLANNED" | "ENDED" | "LIVE";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "LiveSession";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
    liveSessionId: string;
    scheduledAt: string;
}, {
    status: "CANCELLED" | "PLANNED" | "ENDED" | "LIVE";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "LiveSession";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
    liveSessionId: string;
    scheduledAt: string;
}>;
export declare const warehouseObjectSchema: z.ZodObject<{
    warehouseId: z.ZodString;
    name: z.ZodString;
    status: z.ZodEnum<["ACTIVE", "PAUSED", "CLOSED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Warehouse">;
}, "strip", z.ZodTypeAny, {
    status: "CLOSED" | "ACTIVE" | "PAUSED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Warehouse";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    warehouseId: string;
}, {
    status: "CLOSED" | "ACTIVE" | "PAUSED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Warehouse";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    warehouseId: string;
}>;
export declare const customerVocObjectSchema: z.ZodObject<{
    vocId: z.ZodString;
    source: z.ZodString;
    sentiment: z.ZodEnum<["POSITIVE", "NEUTRAL", "NEGATIVE", "UNKNOWN"]>;
    topic: z.ZodString;
    status: z.ZodEnum<["NEW", "CLASSIFIED", "ASSIGNED", "CLOSED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"CustomerVOC">;
}, "strip", z.ZodTypeAny, {
    source: string;
    status: "CLOSED" | "NEW" | "CLASSIFIED" | "ASSIGNED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "CustomerVOC";
    version: "commerce.object.v1";
    updatedAt: string;
    vocId: string;
    sentiment: "UNKNOWN" | "POSITIVE" | "NEUTRAL" | "NEGATIVE";
    topic: string;
}, {
    source: string;
    status: "CLOSED" | "NEW" | "CLASSIFIED" | "ASSIGNED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "CustomerVOC";
    version: "commerce.object.v1";
    updatedAt: string;
    vocId: string;
    sentiment: "UNKNOWN" | "POSITIVE" | "NEUTRAL" | "NEGATIVE";
    topic: string;
}>;
export declare const customerLifecycleObjectSchema: z.ZodObject<{
    customerId: z.ZodString;
    stage: z.ZodEnum<["PROSPECT", "NEW", "ACTIVE", "AT_RISK", "CHURNED", "REACTIVATED"]>;
    status: z.ZodEnum<["OBSERVED", "REVIEW_REQUIRED", "ACTIONED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"CustomerLifecycle">;
}, "strip", z.ZodTypeAny, {
    status: "OBSERVED" | "REVIEW_REQUIRED" | "ACTIONED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "CustomerLifecycle";
    version: "commerce.object.v1";
    updatedAt: string;
    customerId: string;
    stage: "ACTIVE" | "NEW" | "PROSPECT" | "AT_RISK" | "CHURNED" | "REACTIVATED";
}, {
    status: "OBSERVED" | "REVIEW_REQUIRED" | "ACTIONED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "CustomerLifecycle";
    version: "commerce.object.v1";
    updatedAt: string;
    customerId: string;
    stage: "ACTIVE" | "NEW" | "PROSPECT" | "AT_RISK" | "CHURNED" | "REACTIVATED";
}>;
export declare const commerceObjectSchema: z.ZodUnion<[z.ZodObject<{
    name: z.ZodString;
    categoryId: z.ZodString;
    status: z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Product">;
}, "strip", z.ZodTypeAny, {
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Product";
    name: string;
    categoryId: string;
    version: "commerce.object.v1";
    updatedAt: string;
}, {
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Product";
    name: string;
    categoryId: string;
    version: "commerce.object.v1";
    updatedAt: string;
}>, z.ZodObject<{
    skuId: z.ZodString;
    productId: z.ZodString;
    title: z.ZodString;
    status: z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"SKU">;
}, "strip", z.ZodTypeAny, {
    title: string;
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    productId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    skuId: string;
    objectType: "SKU";
    version: "commerce.object.v1";
    updatedAt: string;
}, {
    title: string;
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    productId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    skuId: string;
    objectType: "SKU";
    version: "commerce.object.v1";
    updatedAt: string;
}>, z.ZodObject<{
    name: z.ZodString;
    parentId: z.ZodNullable<z.ZodString>;
    status: z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Category">;
}, "strip", z.ZodTypeAny, {
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Category";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    parentId: string | null;
}, {
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Category";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    parentId: string | null;
}>, z.ZodObject<{
    skuId: z.ZodString;
    warehouseId: z.ZodString;
    available: z.ZodNumber;
    reserved: z.ZodNumber;
    reorderPoint: z.ZodNumber;
    safetyStock: z.ZodNumber;
    status: z.ZodEnum<["HEALTHY", "LOW", "OUT_OF_STOCK", "FROZEN"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Inventory">;
}, "strip", z.ZodTypeAny, {
    status: "HEALTHY" | "LOW" | "OUT_OF_STOCK" | "FROZEN";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    skuId: string;
    available: number;
    reserved: number;
    reorderPoint: number;
    safetyStock: number;
    objectType: "Inventory";
    version: "commerce.object.v1";
    updatedAt: string;
    warehouseId: string;
}, {
    status: "HEALTHY" | "LOW" | "OUT_OF_STOCK" | "FROZEN";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    skuId: string;
    available: number;
    reserved: number;
    reorderPoint: number;
    safetyStock: number;
    objectType: "Inventory";
    version: "commerce.object.v1";
    updatedAt: string;
    warehouseId: string;
}>, z.ZodObject<{
    channelId: z.ZodString;
    platform: z.ZodString;
    shopId: z.ZodString;
    status: z.ZodEnum<["CONNECTED", "READ_ONLY", "DISCONNECTED", "BLOCKED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Channel">;
}, "strip", z.ZodTypeAny, {
    shopId: string;
    status: "BLOCKED" | "CONNECTED" | "READ_ONLY" | "DISCONNECTED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    platform: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Channel";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
}, {
    shopId: string;
    status: "BLOCKED" | "CONNECTED" | "READ_ONLY" | "DISCONNECTED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    platform: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Channel";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
}>, z.ZodObject<{
    orderId: z.ZodString;
    channelId: z.ZodString;
    status: z.ZodEnum<["CREATED", "PAID", "FULFILLING", "COMPLETED", "REFUNDED", "CANCELLED"]>;
    totalAmount: z.ZodNumber;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Order">;
}, "strip", z.ZodTypeAny, {
    status: "CREATED" | "PAID" | "FULFILLING" | "COMPLETED" | "REFUNDED" | "CANCELLED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Order";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
    orderId: string;
    totalAmount: number;
}, {
    status: "CREATED" | "PAID" | "FULFILLING" | "COMPLETED" | "REFUNDED" | "CANCELLED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Order";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
    orderId: string;
    totalAmount: number;
}>, z.ZodObject<{
    caseId: z.ZodString;
    title: z.ZodString;
    status: z.ZodEnum<["OPEN", "INVESTIGATING", "PROPOSED", "WAITING_HUMAN", "APPROVED", "EXECUTING", "VERIFYING", "CLOSED", "BLOCKED"]>;
    triggerEventId: z.ZodString;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"BusinessCase">;
}, "strip", z.ZodTypeAny, {
    title: string;
    status: "CLOSED" | "OPEN" | "INVESTIGATING" | "PROPOSED" | "WAITING_HUMAN" | "APPROVED" | "EXECUTING" | "VERIFYING" | "BLOCKED";
    caseId: string;
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    triggerEventId: string;
    objectType: "BusinessCase";
    version: "commerce.object.v1";
    updatedAt: string;
}, {
    title: string;
    status: "CLOSED" | "OPEN" | "INVESTIGATING" | "PROPOSED" | "WAITING_HUMAN" | "APPROVED" | "EXECUTING" | "VERIFYING" | "BLOCKED";
    caseId: string;
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    triggerEventId: string;
    objectType: "BusinessCase";
    version: "commerce.object.v1";
    updatedAt: string;
}>, z.ZodObject<{
    campaignId: z.ZodString;
    name: z.ZodString;
    status: z.ZodEnum<["PLANNED", "RUNNING", "PAUSED", "ENDED"]>;
    channelIds: z.ZodArray<z.ZodString, "many">;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Campaign">;
}, "strip", z.ZodTypeAny, {
    status: "PAUSED" | "PLANNED" | "RUNNING" | "ENDED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Campaign";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    campaignId: string;
    channelIds: string[];
}, {
    status: "PAUSED" | "PLANNED" | "RUNNING" | "ENDED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Campaign";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    campaignId: string;
    channelIds: string[];
}>, z.ZodObject<{
    liveSessionId: z.ZodString;
    channelId: z.ZodString;
    status: z.ZodEnum<["PLANNED", "LIVE", "ENDED", "CANCELLED"]>;
    scheduledAt: z.ZodString;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"LiveSession">;
}, "strip", z.ZodTypeAny, {
    status: "CANCELLED" | "PLANNED" | "ENDED" | "LIVE";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "LiveSession";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
    liveSessionId: string;
    scheduledAt: string;
}, {
    status: "CANCELLED" | "PLANNED" | "ENDED" | "LIVE";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "LiveSession";
    version: "commerce.object.v1";
    updatedAt: string;
    channelId: string;
    liveSessionId: string;
    scheduledAt: string;
}>, z.ZodObject<{
    warehouseId: z.ZodString;
    name: z.ZodString;
    status: z.ZodEnum<["ACTIVE", "PAUSED", "CLOSED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"Warehouse">;
}, "strip", z.ZodTypeAny, {
    status: "CLOSED" | "ACTIVE" | "PAUSED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Warehouse";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    warehouseId: string;
}, {
    status: "CLOSED" | "ACTIVE" | "PAUSED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "Warehouse";
    name: string;
    version: "commerce.object.v1";
    updatedAt: string;
    warehouseId: string;
}>, z.ZodObject<{
    vocId: z.ZodString;
    source: z.ZodString;
    sentiment: z.ZodEnum<["POSITIVE", "NEUTRAL", "NEGATIVE", "UNKNOWN"]>;
    topic: z.ZodString;
    status: z.ZodEnum<["NEW", "CLASSIFIED", "ASSIGNED", "CLOSED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"CustomerVOC">;
}, "strip", z.ZodTypeAny, {
    source: string;
    status: "CLOSED" | "NEW" | "CLASSIFIED" | "ASSIGNED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "CustomerVOC";
    version: "commerce.object.v1";
    updatedAt: string;
    vocId: string;
    sentiment: "UNKNOWN" | "POSITIVE" | "NEUTRAL" | "NEGATIVE";
    topic: string;
}, {
    source: string;
    status: "CLOSED" | "NEW" | "CLASSIFIED" | "ASSIGNED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "CustomerVOC";
    version: "commerce.object.v1";
    updatedAt: string;
    vocId: string;
    sentiment: "UNKNOWN" | "POSITIVE" | "NEUTRAL" | "NEGATIVE";
    topic: string;
}>, z.ZodObject<{
    customerId: z.ZodString;
    stage: z.ZodEnum<["PROSPECT", "NEW", "ACTIVE", "AT_RISK", "CHURNED", "REACTIVATED"]>;
    status: z.ZodEnum<["OBSERVED", "REVIEW_REQUIRED", "ACTIONED"]>;
    objectId: z.ZodString;
    version: z.ZodLiteral<"commerce.object.v1">;
    tenantId: z.ZodString;
    enterpriseId: z.ZodString;
    brandId: z.ZodString;
    ownerId: z.ZodString;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
    updatedAt: z.ZodString;
    objectType: z.ZodLiteral<"CustomerLifecycle">;
}, "strip", z.ZodTypeAny, {
    status: "OBSERVED" | "REVIEW_REQUIRED" | "ACTIONED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "CustomerLifecycle";
    version: "commerce.object.v1";
    updatedAt: string;
    customerId: string;
    stage: "ACTIVE" | "NEW" | "PROSPECT" | "AT_RISK" | "CHURNED" | "REACTIVATED";
}, {
    status: "OBSERVED" | "REVIEW_REQUIRED" | "ACTIONED";
    tenantId: string;
    enterpriseId: string;
    brandId: string;
    ownerId: string;
    evidenceRefs: string[];
    objectId: string;
    objectType: "CustomerLifecycle";
    version: "commerce.object.v1";
    updatedAt: string;
    customerId: string;
    stage: "ACTIVE" | "NEW" | "PROSPECT" | "AT_RISK" | "CHURNED" | "REACTIVATED";
}>]>;
export declare const productTaskStatusSchema: z.ZodEnum<["OPEN", "IN_PROGRESS", "WAITING_APPROVAL", "APPROVED", "EXECUTING", "VERIFYING", "SUCCEEDED", "FAILED", "BLOCKED", "CLOSED"]>;
export declare const productTaskSchema: z.ZodObject<{
    taskId: z.ZodString;
    caseId: z.ZodString;
    status: z.ZodEnum<["OPEN", "IN_PROGRESS", "WAITING_APPROVAL", "APPROVED", "EXECUTING", "VERIFYING", "SUCCEEDED", "FAILED", "BLOCKED", "CLOSED"]>;
    ownerId: z.ZodString;
    dueAt: z.ZodString;
    acceptanceCriteria: z.ZodArray<z.ZodString, "many">;
    evidenceRefs: z.ZodArray<z.ZodString, "many">;
}, "strip", z.ZodTypeAny, {
    status: "CLOSED" | "OPEN" | "APPROVED" | "EXECUTING" | "VERIFYING" | "BLOCKED" | "IN_PROGRESS" | "WAITING_APPROVAL" | "SUCCEEDED" | "FAILED";
    caseId: string;
    ownerId: string;
    evidenceRefs: string[];
    taskId: string;
    dueAt: string;
    acceptanceCriteria: string[];
}, {
    status: "CLOSED" | "OPEN" | "APPROVED" | "EXECUTING" | "VERIFYING" | "BLOCKED" | "IN_PROGRESS" | "WAITING_APPROVAL" | "SUCCEEDED" | "FAILED";
    caseId: string;
    ownerId: string;
    evidenceRefs: string[];
    taskId: string;
    dueAt: string;
    acceptanceCriteria: string[];
}>;
export type ProductTask = z.infer<typeof productTaskSchema>;
export type ProductObject = z.infer<typeof productObjectSchema>;
export type SkuObject = z.infer<typeof skuObjectSchema>;
export type CategoryObject = z.infer<typeof categoryObjectSchema>;
export type InventoryObject = z.infer<typeof inventoryObjectSchema>;
export type ChannelObject = z.infer<typeof channelObjectSchema>;
export type OrderObject = z.infer<typeof orderObjectSchema>;
export type BusinessCaseObject = z.infer<typeof businessCaseObjectSchema>;
export type CampaignObject = z.infer<typeof campaignObjectSchema>;
export type LiveSessionObject = z.infer<typeof liveSessionObjectSchema>;
export type WarehouseObject = z.infer<typeof warehouseObjectSchema>;
export type CustomerVocObject = z.infer<typeof customerVocObjectSchema>;
export type CustomerLifecycleObject = z.infer<typeof customerLifecycleObjectSchema>;
export type CommerceObject = z.infer<typeof commerceObjectSchema>;
export declare const commerceObjectCatalog: readonly [{
    readonly objectType: "Product";
    readonly purpose: "品牌商品主档与经营状态";
    readonly keyFields: readonly ["productId", "name", "categoryId", "status"];
    readonly statuses: readonly ["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"];
    readonly ownerRole: "商品负责人";
    readonly notResponsibleFor: readonly ["直接发布平台商品"];
    readonly eventTypes: readonly ["product.created", "product.updated"];
}, {
    readonly objectType: "SKU";
    readonly purpose: "可售规格、条码和商品关联";
    readonly keyFields: readonly ["skuId", "productId", "title", "status"];
    readonly statuses: readonly ["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"];
    readonly ownerRole: "商品负责人";
    readonly notResponsibleFor: readonly ["绕过库存校验上架"];
    readonly eventTypes: readonly ["sku.created", "sku.updated"];
}, {
    readonly objectType: "Category";
    readonly purpose: "商品类目与类目基线";
    readonly keyFields: readonly ["categoryId", "name", "parentId", "status"];
    readonly statuses: readonly ["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"];
    readonly ownerRole: "类目负责人";
    readonly notResponsibleFor: readonly ["擅自变更平台类目"];
    readonly eventTypes: readonly ["category.updated"];
}, {
    readonly objectType: "Inventory";
    readonly purpose: "仓库 SKU 库存与补货阈值";
    readonly keyFields: readonly ["skuId", "warehouseId", "available", "reorderPoint", "safetyStock"];
    readonly statuses: readonly ["HEALTHY", "LOW", "OUT_OF_STOCK", "FROZEN"];
    readonly ownerRole: "供应链负责人";
    readonly notResponsibleFor: readonly ["直接下采购单", "直接修改库存"];
    readonly eventTypes: readonly ["inventory.updated", "inventory.threshold.breached"];
}, {
    readonly objectType: "Channel";
    readonly purpose: "销售平台、店铺和授权能力";
    readonly keyFields: readonly ["channelId", "platform", "shopId", "status"];
    readonly statuses: readonly ["CONNECTED", "READ_ONLY", "DISCONNECTED", "BLOCKED"];
    readonly ownerRole: "渠道负责人";
    readonly notResponsibleFor: readonly ["使用未授权凭证写入平台"];
    readonly eventTypes: readonly ["channel.connected", "channel.authorization.changed"];
}, {
    readonly objectType: "Order";
    readonly purpose: "订单与经营结果事实";
    readonly keyFields: readonly ["orderId", "channelId", "status", "totalAmount"];
    readonly statuses: readonly ["CREATED", "PAID", "FULFILLING", "COMPLETED", "REFUNDED", "CANCELLED"];
    readonly ownerRole: "订单运营负责人";
    readonly notResponsibleFor: readonly ["伪造销售结果"];
    readonly eventTypes: readonly ["order.created", "order.signal.created"];
}, {
    readonly objectType: "BusinessCase";
    readonly purpose: "跨部门经营协同单";
    readonly keyFields: readonly ["caseId", "title", "status", "triggerEventId"];
    readonly statuses: readonly ["OPEN", "INVESTIGATING", "PROPOSED", "WAITING_HUMAN", "APPROVED", "EXECUTING", "VERIFYING", "CLOSED", "BLOCKED"];
    readonly ownerRole: "运营协调人";
    readonly notResponsibleFor: readonly ["替代人工决策"];
    readonly eventTypes: readonly ["case.created", "case.status.changed"];
}, {
    readonly objectType: "Campaign";
    readonly purpose: "促销活动及投流活动";
    readonly keyFields: readonly ["campaignId", "name", "status", "channelIds"];
    readonly statuses: readonly ["PLANNED", "RUNNING", "PAUSED", "ENDED"];
    readonly ownerRole: "营销负责人";
    readonly notResponsibleFor: readonly ["未经批准投放或改预算"];
    readonly eventTypes: readonly ["campaign.created", "campaign.status.changed"];
}, {
    readonly objectType: "LiveSession";
    readonly purpose: "直播场次与直播经营信号";
    readonly keyFields: readonly ["liveSessionId", "channelId", "status", "scheduledAt"];
    readonly statuses: readonly ["PLANNED", "LIVE", "ENDED", "CANCELLED"];
    readonly ownerRole: "直播负责人";
    readonly notResponsibleFor: readonly ["未经确认发布直播排期"];
    readonly eventTypes: readonly ["live.started", "live.ended"];
}, {
    readonly objectType: "Warehouse";
    readonly purpose: "仓储节点与履约能力";
    readonly keyFields: readonly ["warehouseId", "name", "status"];
    readonly statuses: readonly ["ACTIVE", "PAUSED", "CLOSED"];
    readonly ownerRole: "仓储负责人";
    readonly notResponsibleFor: readonly ["直接调整仓储主数据"];
    readonly eventTypes: readonly ["warehouse.updated"];
}, {
    readonly objectType: "CustomerVOC";
    readonly purpose: "客户声音、主题和情绪事实";
    readonly keyFields: readonly ["vocId", "source", "sentiment", "topic", "status"];
    readonly statuses: readonly ["NEW", "CLASSIFIED", "ASSIGNED", "CLOSED"];
    readonly ownerRole: "客服负责人";
    readonly notResponsibleFor: readonly ["伪造用户反馈"];
    readonly eventTypes: readonly ["voc.signal.created"];
}, {
    readonly objectType: "CustomerLifecycle";
    readonly purpose: "客户生命周期阶段判断";
    readonly keyFields: readonly ["customerId", "stage", "status"];
    readonly statuses: readonly ["OBSERVED", "REVIEW_REQUIRED", "ACTIONED"];
    readonly ownerRole: "用户运营负责人";
    readonly notResponsibleFor: readonly ["未经授权触达客户"];
    readonly eventTypes: readonly ["customer.lifecycle.changed"];
}];
