import type { IncomingMessage, ServerResponse } from 'node:http'
import { existsSync } from 'node:fs'
import { readFile, stat } from 'node:fs/promises'
import { extname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { XinianService } from './service.js'

export interface XinianWebServer { readonly port: number; register(route: { kind: 'exact' | 'prefix'; path: string; handler: (req: IncomingMessage, res: ServerResponse) => void | Promise<void> }): () => void }
function json(res: ServerResponse, status: number, value: unknown) { res.statusCode = status; res.setHeader('content-type', 'application/json; charset=utf-8'); res.setHeader('cache-control', 'no-store'); res.end(JSON.stringify(value)) }
function error(res: ServerResponse, status: number, code: string, message: string) { json(res, status, { error: { code, message }, requestId: crypto.randomUUID() }) }
function sameOrigin(req: IncomingMessage, port: number) { return req.headers.origin === undefined || req.headers.origin === `http://127.0.0.1:${String(port)}` }
async function body(req: IncomingMessage): Promise<Record<string, unknown>> { const chunks: Buffer[] = []; let size = 0; for await (const chunk of req) { const b = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk); size += b.length; if (size > 512 * 1024) throw new Error('request body too large'); chunks.push(b) }; const value: unknown = JSON.parse(Buffer.concat(chunks).toString('utf8')); if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('request body must be an object'); return value as Record<string, unknown> }

export function registerXinianRoutes(server: XinianWebServer, service = new XinianService()): () => void {
  const api = '/api/xinian'; const registrations = [
    server.register({ kind: 'exact', path: `${api}/health`, handler: (req, res) => { if (req.method !== 'GET' || !sameOrigin(req, server.port)) return error(res, 405, 'METHOD_NOT_ALLOWED', 'health requires GET'); json(res, 200, service.health()) } }),
    server.register({ kind: 'exact', path: `${api}/dashboard`, handler: (_req, res) => json(res, 200, service.dashboard()) }),
    server.register({ kind: 'exact', path: `${api}/products`, handler: async (req, res) => { if (!sameOrigin(req, server.port)) return error(res, 403, 'ORIGIN_DENIED', 'same-origin request required'); try { if (req.method === 'GET') return json(res, 200, { products: service.products.list() }); if (req.method !== 'POST') return error(res, 405, 'METHOD_NOT_ALLOWED', 'products supports GET or POST'); const data = await body(req); const product = service.products.create({ title: String(data.title ?? ''), category: String(data.category ?? ''), price: Number(data.price), assetPaths: Array.isArray(data.assetPaths) ? data.assetPaths.map(String) : [], ...(typeof data.description === 'string' ? { description: data.description } : {}) }); return json(res, 201, { product }) } catch (cause) { return error(res, 400, 'INVALID_REQUEST', cause instanceof Error ? cause.message : String(cause)) } } }),
    server.register({ kind: 'exact', path: `${api}/tasks`, handler: async (req, res) => { if (req.method === 'GET') return json(res, 200, { tasks: service.tasks.list() }); if (req.method !== 'POST') return error(res, 405, 'METHOD_NOT_ALLOWED', 'tasks supports GET or POST'); try { const data = await body(req); const productId = typeof data.productId === 'string' ? data.productId : undefined; const task = service.tasks.create({ type: data.type === 'publish' || data.type === 'analytics' || data.type === 'full_workflow' ? data.type : 'content', ...(productId ? { productId } : {}), storeIds: Array.isArray(data.storeIds) ? data.storeIds.map(String) : [], input: data.input && typeof data.input === 'object' ? data.input as Record<string, unknown> : {}, approvalRequired: data.approvalRequired === true }); const missing = task.type === 'content' && !productId; const result = missing ? service.tasks.transition(task.id, 'WAITING_INPUT', 'control-plane', 'productId is required') : task; return json(res, 201, { task: result }) } catch (cause) { return error(res, 400, 'INVALID_REQUEST', cause instanceof Error ? cause.message : String(cause)) } } }),
    server.register({ kind: 'prefix', path: `${api}/tasks/`, handler: (req, res) => { const match = new URL(req.url ?? '/', `http://127.0.0.1:${String(server.port)}`).pathname.match(new RegExp(`^${api}/tasks/([^/]+)(?:/(events|artifacts|checkpoint))?$`)); if (!match || req.method !== 'GET') return error(res, 404, 'NOT_FOUND', 'task endpoint not found'); try { const task = service.tasks.get(match[1]!); if (match[2] === 'events') return json(res, 200, { events: service.tasks.events(task.id) }); if (match[2] === 'artifacts') return json(res, 200, { artifacts: task.outputs }); if (match[2] === 'checkpoint') return json(res, 200, { checkpoint: task.checkpoint ?? null }); return json(res, 200, { task }) } catch (cause) { return error(res, 404, 'TASK_NOT_FOUND', cause instanceof Error ? cause.message : String(cause)) } } }),
    server.register({ kind: 'exact', path: `${api}/content/generate`, handler: async (req, res) => { if (req.method !== 'POST') return error(res, 405, 'METHOD_NOT_ALLOWED', 'content generation requires POST'); try { const data = await body(req); if (typeof data.productId !== 'string' || !data.productId) return error(res, 400, 'MISSING_INPUT', 'productId is required'); return json(res, 201, await service.content.generate(data.productId)) } catch (cause) { return error(res, 400, 'INVALID_REQUEST', cause instanceof Error ? cause.message : String(cause)) } } }),
    server.register({ kind: 'exact', path: `${api}/publish/preview`, handler: async (req, res) => { if (req.method !== 'POST') return error(res, 405, 'METHOD_NOT_ALLOWED', 'publish preview requires POST'); try { const data = await body(req); return json(res, 200, service.publish.preview(String(data.productId ?? ''), Array.isArray(data.storeIds) ? data.storeIds.map(String) : [])) } catch (cause) { return error(res, 400, 'INVALID_REQUEST', cause instanceof Error ? cause.message : String(cause)) } } }),
    server.register({ kind: 'exact', path: `${api}/publish/execute`, handler: async (req, res) => { if (req.method !== 'POST') return error(res, 405, 'METHOD_NOT_ALLOWED', 'publish execute requires POST'); try { const data = await body(req); return json(res, 200, service.publish.execute(String(data.productId ?? ''), Array.isArray(data.storeIds) ? data.storeIds.map(String) : [], data.approved === true)) } catch (cause) { return error(res, 409, 'PUBLISH_BLOCKED', cause instanceof Error ? cause.message : String(cause)) } } }),
    server.register({ kind: 'exact', path: `${api}/stores`, handler: (_req, res) => json(res, 200, { stores: [{ id: 'douyin-demo', name: '抖店', status: 'disconnected' }, { id: 'kuaishou-demo', name: '快手小店', status: 'disconnected' }, { id: 'wechat-demo', name: '微信小店', status: 'disconnected' }] }) }),
    server.register({ kind: 'exact', path: `${api}/analytics/overview`, handler: (_req, res) => json(res, 200, service.analytics.overview()) }),
    server.register({ kind: 'exact', path: `${api}/analytics/orders`, handler: (_req, res) => json(res, 200, { source: 'mock', orders: [] }) }),
    server.register({ kind: 'exact', path: `${api}/analytics/content-performance`, handler: (_req, res) => json(res, 200, { source: 'mock', items: [] }) }),
  ]; return () => registrations.forEach(unregister => unregister())
}

const WORKBENCH = '/xinian-commerce'
const TYPES: Record<string, string> = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png' }
function workbenchRoot(): string { return resolve(process.env.DSH_XINIAN_COMMERCE_DIST?.trim() || fileURLToPath(new URL('../../dist', import.meta.url))) }
async function serveWorkbench(req: IncomingMessage, res: ServerResponse): Promise<void> {
  const pathname = new URL(req.url ?? '/', 'http://localhost').pathname
  const suffix = pathname === WORKBENCH || pathname === `${WORKBENCH}/` ? 'index.html' : pathname.slice(`${WORKBENCH}/`.length)
  let decoded = ''; try { decoded = decodeURIComponent(suffix) } catch { return error(res, 400, 'INVALID_PATH', 'invalid asset path') }
  if (!decoded || decoded.includes('..') || decoded.includes('\\') || decoded.includes('\u0000')) return error(res, 400, 'INVALID_PATH', 'invalid asset path')
  const root = resolve(workbenchRoot()); const filename = resolve(root, decoded); const rel = relative(root, filename)
  if (rel.startsWith('..') || rel.includes('\\')) return error(res, 400, 'INVALID_PATH', 'invalid asset path')
  try { const info = await stat(filename); if (!info.isFile()) throw new Error('not file'); const content = await readFile(filename); res.statusCode = 200; res.setHeader('content-type', TYPES[extname(filename).toLowerCase()] ?? 'application/octet-stream'); res.end(content) } catch { error(res, 404, 'ASSET_NOT_FOUND', 'workbench asset not found') }
}
export function registerXinianWorkbench(server: XinianWebServer): () => void {
  if (!existsSync(workbenchRoot())) { /* The source tree may be unbuilt; the route remains registered for the build output. */ }
  const registrations = [server.register({ kind: 'exact', path: WORKBENCH, handler: (_req, res) => { res.statusCode = 302; res.setHeader('location', `${WORKBENCH}/`); res.end() } }), server.register({ kind: 'prefix', path: `${WORKBENCH}/`, handler: serveWorkbench })]
  return () => registrations.forEach(unregister => unregister())
}
