import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { api } from '../api.js';
export function ContentStudioPage({ onTask }) { const [productId, setProductId] = useState('demo-product'); const [message, setMessage] = useState(''); const generate = async () => { try {
    const result = await api.generate(productId);
    setMessage(`任务已完成：${result.verification.delivery}`);
}
catch (error) {
    setMessage(error instanceof Error ? error.message : '生成失败');
} }; return _jsxs("div", { className: "xn-page-card", children: [_jsxs("div", { className: "xn-section-head", children: [_jsxs("div", { children: [_jsx("span", { className: "xn-eyebrow", children: "CONTENT STUDIO" }), _jsx("h2", { children: "\u5185\u5BB9\u751F\u4EA7" })] }), _jsx("span", { className: "xn-status-pill running", children: "\u25CF Mock Agent \u53EF\u7528" })] }), _jsxs("div", { className: "xn-studio-layout", children: [_jsxs("div", { className: "xn-prompt-card", children: [_jsx("label", { children: "\u9009\u62E9\u5546\u54C1\u6863\u6848" }), _jsx("input", { value: productId, onChange: event => setProductId(event.target.value) }), _jsx("label", { children: "\u751F\u4EA7\u7C7B\u578B" }), _jsxs("div", { className: "xn-choice-grid", children: [_jsx("button", { className: "is-selected", children: "\u2726 \u4E3B\u56FE\u5957\u88C5" }), _jsx("button", { children: "\u25A4 \u8BE6\u60C5\u9875" }), _jsx("button", { children: "\u25B6 \u5E26\u8D27\u89C6\u9891" }), _jsx("button", { children: "\u270E \u5356\u70B9\u6587\u6848" })] }), _jsxs("button", { className: "xn-primary full", onClick: generate, children: ["\u542F\u52A8\u5185\u5BB9 Agent ", _jsx("span", { children: "\u2192" })] }), message && _jsx("p", { className: "xn-notice", children: message })] }), _jsxs("div", { className: "xn-preview-card", children: [_jsxs("div", { className: "xn-preview-glow", children: ["AI", _jsx("br", {}), _jsx("small", { children: "\u7B49\u5F85\u5185\u5BB9\u751F\u6210" })] }), _jsx("span", { children: "OUTPUT PREVIEW" }), _jsx("b", { children: "\u5B8C\u6210\u4EFB\u52A1\u540E\uFF0C\u7ED3\u679C\u4F1A\u51FA\u73B0\u5728\u8FD9\u91CC" })] })] }), _jsx("button", { className: "xn-secondary", onClick: () => onTask('latest'), children: "\u6253\u5F00\u8FD0\u884C\u68C0\u67E5\u5668" })] }); }
