/** Isolated shadcn-backed Desktop dialog rendered as a modal BrowserWindow. */

import { screen } from 'electron'
import type { BrowserWindow, MessageBoxOptions, MessageBoxReturnValue } from 'electron'
import { fileURLToPath } from 'node:url'
import {
  auxiliaryWindowChromeOptions,
  auxiliaryWindowHasCustomFrame,
} from './auxiliary-window-options.ts'
import { revealApplication } from './electron-reveal.ts'
import { createDesktopLocalWindow } from './local-window-policy.ts'
import { DESKTOP_PRODUCT_NAME } from './product-identity.ts'

const DIALOG_SCHEME = 'dsh-desktop-dialog:'
const DIALOG_DOCUMENT = fileURLToPath(new URL('./native-ui/desktop-dialog.html', import.meta.url))
const MAX_BUTTONS = 4
const DIALOG_WIDTH = 480
const DIALOG_INITIAL_HEIGHT = 300
const DIAGNOSTIC_DIALOG_WIDTH = 680
const DIAGNOSTIC_DIALOG_INITIAL_HEIGHT = 460
/** Electron omits the 2rem shadcn action row from the reported preferred height. */
const DIALOG_PREFERRED_HEIGHT_OFFSET = 32
const DIALOG_REVEAL_FALLBACK_MS = 250

/** Windows and the content-sized compatibility notice already include the action row. */
export function desktopDialogPreferredHeight(
  preferredHeight: number,
  platform: NodeJS.Platform = process.platform,
  presentation: DesktopDialogOptions['presentation'] = 'default',
): number {
  return preferredHeight + (platform === 'win32' || presentation === 'profile-compatibility'
    ? 0 : DIALOG_PREFERRED_HEIGHT_OFFSET)
}

/**
 * Center a dialog over its parent window, clamped into the work area of the
 * display that contains the parent.
 *
 * Electron centers a new window without an explicit position on the display
 * nearest the freshly created, still hidden window - which sits at the
 * virtual-desktop origin, i.e. the primary display. A parented dialog left to
 * that default therefore opens on the primary monitor whenever the parent
 * lives on a secondary one, so parented dialogs must carry an explicit
 * position computed from the parent's own bounds.
 */
export function desktopDialogPosition(
  parentBounds: Electron.Rectangle,
  size: { readonly width: number; readonly height: number },
  workArea: Electron.Rectangle,
): { x: number; y: number } {
  const centerX = Math.round(parentBounds.x + (parentBounds.width - size.width) / 2)
  const centerY = Math.round(parentBounds.y + (parentBounds.height - size.height) / 2)
  return {
    x: workArea.width >= size.width
      ? Math.min(Math.max(centerX, workArea.x), workArea.x + workArea.width - size.width)
      : workArea.x,
    y: workArea.height >= size.height
      ? Math.min(Math.max(centerY, workArea.y), workArea.y + workArea.height - size.height)
      : workArea.y,
  }
}

export interface DesktopDialogOptions {
  readonly type?: 'none' | 'info' | 'error' | 'question' | 'warning'
  readonly title: string
  readonly message: string
  readonly detail?: string
  /** Important guidance rendered after the detail instead of inside its scroll area. */
  readonly advisory?: string
  readonly buttons: readonly string[]
  readonly defaultId?: number
  readonly cancelId?: number
  /** Use a larger shadcn scroll surface for bounded technical diagnostics. */
  readonly presentation?: 'default' | 'diagnostic' | 'profile-compatibility'
  /** Override whether this dialog exposes native close/caption controls. */
  readonly windowControls?: boolean
}

export interface DesktopDialogResult {
  readonly response: number
}

function normalizedIndex(value: number | undefined, fallback: number, length: number): number {
  return value !== undefined && Number.isSafeInteger(value) && value >= 0 && value < length
    ? value
    : fallback
}

/** Parse only a bounded response generated by the local dialog document. */
export function parseDesktopDialogResponse(href: string, buttonCount: number): number | undefined {
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== DIALOG_SCHEME || url.hostname !== 'response'
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== ''
    || [...url.searchParams.keys()].some(key => key !== 'id')) return undefined
  const raw = url.searchParams.get('id')
  if (raw === null || !/^(?:0|[1-9]\d*)$/u.test(raw)) return undefined
  const response = Number(raw)
  return Number.isSafeInteger(response) && response >= 0 && response < buttonCount ? response : undefined
}

/** One-shot modal Desktop window; closing it always produces the cancel result. */
export class DesktopDialogWindow {
  constructor(
    private readonly options: DesktopDialogOptions,
    private readonly parent?: BrowserWindow,
  ) {}

  async run(): Promise<DesktopDialogResult> {
    if (this.options.buttons.length === 0 || this.options.buttons.length > MAX_BUTTONS) {
      throw new Error(`dsh-plugin-desktop: Desktop dialog requires 1-${String(MAX_BUTTONS)} buttons`)
    }
    const cancelId = normalizedIndex(this.options.cancelId, this.options.buttons.length - 1, this.options.buttons.length)
    const defaultId = normalizedIndex(this.options.defaultId, 0, this.options.buttons.length)
    const state = Buffer.from(JSON.stringify({
      type: this.options.type ?? 'none',
      title: this.options.title,
      message: this.options.message,
      ...(this.options.detail === undefined ? {} : { detail: this.options.detail }),
      ...(this.options.advisory === undefined ? {} : { advisory: this.options.advisory }),
      buttons: this.options.buttons,
      defaultId,
      cancelId,
      presentation: this.options.presentation ?? 'default',
    }), 'utf8').toString('base64url')
    const parent = this.parent !== undefined && !this.parent.isDestroyed() ? this.parent : undefined
    // Parented modal dialogs are action surfaces, not independently navigable
    // windows. They stay frameless unless a caller explicitly opts into native
    // controls; standalone notices keep ordinary close controls.
    const windowControls = this.options.windowControls ?? parent === undefined
    const customFrame = auxiliaryWindowHasCustomFrame(process.platform, windowControls)
    const diagnostic = this.options.presentation === 'diagnostic'
    const dialogWidth = diagnostic ? DIAGNOSTIC_DIALOG_WIDTH : DIALOG_WIDTH
    const initialHeight = diagnostic ? DIAGNOSTIC_DIALOG_INITIAL_HEIGHT : DIALOG_INITIAL_HEIGHT
    // A parented dialog must be positioned explicitly: Electron centers a
    // window without x/y on the primary display (the display nearest the
    // hidden window at creation), which strands the dialog on the wrong
    // monitor whenever the parent sits on a secondary display.
    const dialogPosition = parent === undefined
      ? undefined
      : desktopDialogPosition(
          parent.getBounds(),
          { width: dialogWidth, height: initialHeight },
          screen.getDisplayMatching(parent.getBounds()).workArea,
        )
    const window = createDesktopLocalWindow({
      partition: 'dsh-desktop-dialog',
      preferredSizeMode: true,
      title: this.options.title,
      ...auxiliaryWindowChromeOptions(process.platform, windowControls),
      width: dialogWidth,
      height: initialHeight,
      ...(dialogPosition === undefined ? {} : dialogPosition),
      useContentSize: true,
      minWidth: diagnostic ? 560 : 420,
      maxWidth: diagnostic ? 860 : 620,
      resizable: windowControls,
      maximizable: false,
      fullscreenable: false,
      show: false,
      autoHideMenuBar: true,
      backgroundColor: '#202124',
      ...(parent === undefined ? {} : { parent, modal: true, skipTaskbar: true }),
    })
    window.accessibleTitle = this.options.title
    window.removeMenu()

    return await new Promise<DesktopDialogResult>((resolve, reject) => {
      let settled = false
      let documentLoaded = false
      let paintReady = false
      let layoutReady = false
      let revealed = false
      let preferredHeight: number | undefined
      let appliedHeight: number | undefined
      let revealTimer: ReturnType<typeof setTimeout> | undefined
      const reveal = (): void => {
        if (revealed || !documentLoaded || !paintReady || window.isDestroyed()) return
        revealed = true
        if (revealTimer !== undefined) clearTimeout(revealTimer)
        revealTimer = undefined
        if (parent !== undefined) {
          // Re-center with the actual bounds: the creation-time position only
          // knew the initial height, and preferred-size resizing grows the
          // window downward from its top-left corner.
          const bounds = window.getBounds()
          const position = desktopDialogPosition(
            bounds,
            { width: bounds.width, height: bounds.height },
            screen.getDisplayMatching(bounds).workArea,
          )
          window.setPosition(position.x, position.y)
        }
        revealApplication(window)
      }
      const finish = (response: number): void => {
        if (settled) return
        settled = true
        if (revealTimer !== undefined) clearTimeout(revealTimer)
        if (!window.isDestroyed()) window.destroy()
        resolve(Object.freeze({ response }))
      }
      const scheduleReveal = (): void => {
        if (!documentLoaded || !paintReady || revealed) return
        if (layoutReady) {
          reveal()
        } else if (revealTimer === undefined) {
          revealTimer = setTimeout(reveal, DIALOG_REVEAL_FALLBACK_MS)
        }
      }
      const applyPreferredSize = (): void => {
        if (!documentLoaded || preferredHeight === undefined || window.isDestroyed()) return
        const height = preferredHeight
        layoutReady = true
        if (height === appliedHeight) {
          scheduleReveal()
          return
        }
        appliedHeight = height
        // Keep this as one content-area resize. On macOS modal sheets the
        // native geometry update can lag this call; reading outer bounds and
        // writing them back immediately can restore the stale, shorter height.
        window.setContentSize(dialogWidth, height, false)
        scheduleReveal()
      }
      const navigate = (event: Electron.Event, href: string): void => {
        event.preventDefault()
        const response = parseDesktopDialogResponse(href, this.options.buttons.length)
        if (response !== undefined) finish(response)
      }
      window.webContents.on('will-navigate', navigate)
      window.webContents.on('will-redirect', navigate)
      window.webContents.on('preferred-size-changed', (_event, size) => {
        if (!Number.isSafeInteger(size.height) || size.height <= 0) return
        preferredHeight = desktopDialogPreferredHeight(size.height, process.platform, this.options.presentation)
        applyPreferredSize()
      })
      window.webContents.on('did-finish-load', () => {
        documentLoaded = true
        applyPreferredSize()
        scheduleReveal()
      })
      window.once('ready-to-show', () => {
        paintReady = true
        scheduleReveal()
      })
      window.on('closed', () => { finish(cancelId) })
      void window.loadFile(DIALOG_DOCUMENT, {
        query: {
          state,
          platform: process.platform,
          frame: String(customFrame),
        },
      }).catch((cause: unknown) => {
        if (settled) return
        settled = true
        if (revealTimer !== undefined) clearTimeout(revealTimer)
        if (!window.isDestroyed()) window.destroy()
        reject(cause)
      })
    })
  }
}

/** Render a Desktop-level modal window instead of an in-page overlay. */
export async function showDesktopDialog(
  options: DesktopDialogOptions,
  parent?: BrowserWindow,
): Promise<DesktopDialogResult> {
  return await new DesktopDialogWindow(options, parent).run()
}

/** Electron MessageBox-compatible adapter backed by the Desktop dialog window. */
export async function showDesktopMessageBox(
  options: MessageBoxOptions,
  parent?: BrowserWindow,
): Promise<MessageBoxReturnValue> {
  const result = await showDesktopDialog({
    type: options.type ?? 'none',
    title: options.title ?? DESKTOP_PRODUCT_NAME,
    message: options.message,
    ...(options.detail === undefined ? {} : { detail: options.detail }),
    buttons: options.buttons ?? ['OK'],
    ...(options.defaultId === undefined ? {} : { defaultId: options.defaultId }),
    ...(options.cancelId === undefined ? {} : { cancelId: options.cancelId }),
  }, parent)
  return Object.freeze({ response: result.response, checkboxChecked: false })
}
